spring:
  config:
    import: file:config/secrets.yaml

  application:
    name: tg-notification

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  cloud:
    service-registry:
      auto-registration:
        enabled: false

telegram:
  bot:
    username: TaxiDriverNotify

mq:
  ride-notifications:
    send:
      queue: ride-notifications.send.queue

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true