spring.config.import=file:config/secrets.properties

spring.application.name=ride

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

ride.status.allowed-transitions={'CREATED': {'ACCEPTED', 'CANCELED'}, 'ACCEPTED': {'DRIVING_TO_PASSENGER', 'CANCELED'}, 'DRIVING_TO_PASSENGER': {'DRIVING_TO_DESTINATION', 'CANCELED'}, 'DRIVING_TO_DESTINATION': {'COMPLETED', 'CANCELED'}, 'COMPLETED': {}, 'CANCELED': {}}